### ISSUE TITLE
SCRIPT1028: SCRIPT1028: Expected identifier, string or number

### ISSUE THREAD

**Issue by gitlabisbetterthangithub** [malchata/yall.js#25] opened 2018-08-02 07:32 UTC
Microsoft Edge error
```javascript
SCRIPT1028: SCRIPT1028: Expected identifier, string or number
yall.js (137,5)
```

I also get
```javascript
SCRIPT5009: SCRIPT5009: 'yall' is not defined
```

My document works sort of in Google Chrome (see #24) but in Microsoft Edge, any images that are controlled with `yall.js` are not working.

My code
```html
<img class="lazy" alt="alt text" src="img/placeholder.jpg" data-src="img/image.jpg">
```

Just before closing body tag (`</body>`)
```html
<script src="js/yall.js"></script>
<script>document.addEventListener("DOMContentLoaded", yall);</script>
```

**Comment by malchata** [comment] 2018-08-02 20:49
I have been able to reproduce these issues when using the non-minified source in Edge, but I don't encounter them when I use the minified production build. There are several language features used in the untranspiled source that may not be compatible in all browsers that get transpiled to more widely compatible code in the production build.

For example, when I run the source build in Edge, it gives me these two errors, the first of which points to a line using [spread syntax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax) to merge user-supplied options with the defaults. This works in browsers like Chrome, but not Edge (and perhaps others).

Because I can't reproduce these specific issues using the recommended production build, I'm marking this ticket with the appropriate labels and closing it. If you want to perform debugging using the minified source, please generate a [source map](https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Use_a_source_map) (which is can be done with uglify-js's `--source-map` option).

I will still look into #24 as soon as I'm able.

**Closed** 2018-08-02 20:50 UTC
Labels: invalid, wontfix

**Comment by gitlabisbetterthangithub** [comment] 2018-08-03 07:26
Okay great thanks.

I am now using lozad.js but if #24 can be fixed, I may switch back. I especially like how your library supports Safari.

**Comment by SylvainMarty** [comment] 2019-03-18 16:26
Hello @malchata, I've been facing this same issue on Microsoft Edge.
Like you said, it's caused by the spread operator not compatible on Edge.
Is it possible to add the Babel plugin [`babel-plugin-proposal-object-rest-spread`](https://babeljs.io/docs/en/babel-plugin-proposal-object-rest-spread) to the rollup configuration ? I'm able to purpose a PR which will fix that if you're okay with this solution.

For now, I've saved locally the `dist/yall.js` script and edited it to remove the only spread operator but its not very scalable...

Thank you in advance !

**Comment by malchata** [comment] 2019-03-19 02:56
Hi, @SylvainMarty. Thanks for logging this.

As of version 2.3.0, yall.js no longer uses the spread operator. So you should be able to use this now.

Hope this helps!
